services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trazabilidad-laravel
    volumes:
      - .:/var/www
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db       # Nombre del servicio del contenedor de postgres
      DB_PORT: 5432
      DB_DATABASE: trazabilidad_db
      DB_USERNAME: admin
      DB_PASSWORD: admin123
      CLOUDINARY_CLOUD_NAME: dtnweo7db
      CLOUDINARY_API_KEY: 576298653297422
      CLOUDINARY_API_SECRET: O-z365d0P_j26ZZb8HaKNeypO3U
      PRODUCTORES_API_URL: http://productores.dasalas.shop/api
      TRAZABILIDAD_API_URL: https://orgtrack.dasalas.shop/api
      HELPDESK_API_URL: https://proyecto-de-ultimo-minuto.online
    depends_on:
      - db
    networks:
      - trazabilidad-net
  nginx:
    image: nginx:latest
    container_name: trazabilidad
    expose:
      - "80"
    # ports:
    #   - "8080:80" #---> despliegue local con puerto 8080
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel
    networks:
      - trazabilidad-net
      - internal-network
      - proxy-network
  db:
    image: postgres:latest
    container_name: trazabilidad-db
    restart: unless-stopped
    # ports:
    #   - "5434:5432"
    environment:
      POSTGRES_DB: trazabilidad_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - db-data:/var/lib/postgresql
    networks:
      - trazabilidad-net

networks:
  trazabilidad-net:
    driver: bridge
  internal-network:
    external: true
  proxy-network:
    external: true
    
volumes:
  db-data: